### ISSUE TITLE
Upgrading from 0.4.1 to 0.4.5 pex issue no module named ...

### ISSUE THREAD

**Issue by blankdots** [linkedin/pygradle#122]
First of all thanks for PyGradle, been using it successfully for the past few months. I also kept a close eye on new releases, which brings me to the issue I encountered.

While trying to build a CLI python app using the pygradle `com.linkedin.python-cli` plugin 0.4.5 version, I noticed that it stopped working. I mean  stopped working  because building with version 0.4.1 it still works. 

To replicate this issue one can use the https://github.com/linkedin/pygradle/tree/master/examples/iris-classification to do this.

The only lines I modified in the example are the ones related to the version and obviously the ivy repository. The version bump:
```
plugins {
  id "com.linkedin.python-cli" version "0.4.5"
}
```
The result:
```
$ ./build/deployable/bin/classify_iris 
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 324, in execute
  File ".bootstrap/_pex/pex.py", line 257, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 289, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 363, in _execute
  File ".bootstrap/_pex/pex.py", line 425, in execute_entry
  File ".bootstrap/_pex/pex.py", line 439, in execute_pkg_resources
  File ".bootstrap/pkg_resources/__init__.py", line 2386, in resolve
ImportError: No module named classify_iris.run
```

It seems like a temporary solution after much fiddling around with dependencies is to revert back to pip 7.1.2 (pygradle 0.4.5 version uses 9.0.1):
```
python {
    forceVersion('pypi', 'pip', '7.1.2')
}
```
While I tried identifying the issue it seems to be pex related (maybe to be fixed with this: https://github.com/linkedin/pygradle/pull/110). Any other suggestions would be welcomed or if there is another workaround.

Thanks.

**Comment by ethankhall** [comment]
@blankdots thanks for the report!

@zvezdan i think we should roll back to using 7.1.2, what do you think? / Do you have other options?

**Comment by zvezdan** [comment]
@ethankhall I was not even aware that it was bumped to 9.0.1.
Please do revert.
As you know I'm testing various updates internally right now.
When we have a known good set I'll update here too.
