### ISSUE TITLE
Install product requirements after test requirements

### ISSUE THREAD

**Issue by schakrava** [linkedin/pygradle#158]
Currently we install test requirements after product requirements. If a same dependency is declared in both, but versions are different, the version in test requirements wins. Flip the order to make sure product requirements take precedence.

**Comment by zsimic** [comment]
Could we restore support for custom arguments to pass through to `py.test`?
The following does not work anymore with 0.6.11:

```
pytest {
    // This allows to generate a junit-like test report, with log capturing
    //extraArgs = ['--junit-xml', 'build/reports/TEST-report.xml', '--capture=fd']
}
```

**Comment by schakrava** [comment]
Hi @zsimic . I've renamed `extraArgs` to `additionalArguments`. Sorry for breaking your build, but could you change to:

```
pytest {
    // This allows to generate a junit-like test report, with log capturing
    additionalArguments = ['--junit-xml', 'build/reports/TEST-report.xml', '--capture=fd']
}
```

**Comment by zsimic** [comment]
Awesome, thanks a lot!
Yes indeed, I missed the new one somehow (I read the corresponding file, but missed this), thanks for pointing it out. It works great.
