### ISSUE TITLE
Support for pulling "bdist_wheel" into ivy format

### ISSUE THREAD

**Issue by qlan2** [linkedin/pygradle#186]
It seems currently pivy-importer only supports to pull "sdist" format for PyPI, and now wheels is getting more and more popular and useful. Could you guys also support to pull wheels packages locally into an Ivy format as well? That would be very helpful! Thanks!

**Comment by sixninetynine** [comment]
This is an issue that's near and dear to our hearts as well... it would dramatically speed up builds too!

**Comment by qlan2** [comment]
This feature has been implemented in https://github.com/linkedin/pygradle/pull/230
