### ISSUE TITLE
Bring back the PythonWheelDistributionPlugin

### ISSUE THREAD

**Issue by ameliedagenais** [linkedin/pygradle#204]
It looks like the PythonWheelDistributionPlugin was removed from the latest version of Pygradle: https://github.com/linkedin/pygradle/commit/9ad8e104d8f47cd130f9ee82754a616080c714ac#diff-3150c245427f4dba770f943d6d924412L9. Can you guys bring it back? We would like to be able to publish wheel package artifacts for our projects and it used to just work by calling the `packageWheel` task. This task is no longer available with version 0.7.7.

**Comment by kopy07** [comment]
@ameliedagenais sorry about that! Would you also like a nice plugin name for the plugin so you could do `apply plugin: 'python-wheel-dist'`?

**Comment by ameliedagenais** [comment]
@ethankhall Yes that would be nice! The documentation around this plugin and the WheelsFirstPlugin could also be updated.

**Comment by kopy07** [comment]
Do you like the name, or do you have some other ideas for it?

Good point. I'll add some docs too. I'm not quite ready to promote it to "prod" (should be in the next week or so when I feel ready for that). Once that happens, it will get a nice name that you can apply vs using the class name.

If you have any other classes you're using as a FQDN let me know, and we can make them "public".

**Comment by ethankhall** [comment]
@ameliedagenais can you take a look at #212 and see if that will solve this one (I'll work on docs here soon)

**Comment by ameliedagenais** [comment]
Yes, looks good to me.

**Comment by kopy07** [comment]
We've merged this, so I'll close this one out. Let me know if you run into anything else because of it!
