### ISSUE TITLE
java.io.NotSerializableException: com.linkedin.gradle.python.util.OperatingSystem$Linux

### ISSUE THREAD

**Issue by chrisbrake** [linkedin/pygradle#205]
When I was trying to build some custom tasks around building virtual environments I discovered that if I declared outputs, the task would fail.

I've created a branch for reference, and reproduced the issue in the [example-project](https://github.com/chrisbrake/pygradle/tree/master/examples/example-project).

Here's a sample of what the error looks like
```
$ gradle installPythonRequirementsInAnotherVenv

FAILURE: Build failed with an exception.

* What went wrong:
Unable to store input properties for task ':installPythonRequirementsInAnotherVenv'. Property 'pythonDetails' with value 'com.linkedin.gradle.python.extension.PythonDetails@601bcc16' cannot be serialized.
> java.io.NotSerializableException: com.linkedin.gradle.python.util.OperatingSystem$Linux

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
6 actionable tasks: 2 executed, 4 up-to-date
```
 To suppress the error, just comment out [this line](https://github.com/chrisbrake/pygradle/blob/20747d4dc94ddb65e6fd4d479f10c502c85a7e02/examples/example-project/build.gradle#L48).

From what I can see OperatingSystem is never serializable, but Gradle only tries to serialize it when outputs are declared for the task.

**Comment by chrisbrake** [comment]
I was playing around with this, this evening.  

I found I was able to resolve this by Removing the Input decorator from the [packageExcludeFilter attribute in PipInstallTask.groovy](https://github.com/linkedin/pygradle/blob/1a560da6d9f0b145c8c3bcc8c09a9cc119e608e6/pygradle-plugin/src/main/groovy/com/linkedin/gradle/python/tasks/PipInstallTask.groovy#L86), and also marking the [virtualEnvironment](https://github.com/linkedin/pygradle/blob/1a560da6d9f0b145c8c3bcc8c09a9cc119e608e6/pygradle-plugin/src/main/groovy/com/linkedin/gradle/python/extension/PythonDetails.java#L34), [pythonDefaultVersions](https://github.com/linkedin/pygradle/blob/1a560da6d9f0b145c8c3bcc8c09a9cc119e608e6/pygradle-plugin/src/main/groovy/com/linkedin/gradle/python/extension/PythonDetails.java#L39), [operatingSystem](https://github.com/linkedin/pygradle/blob/1a560da6d9f0b145c8c3bcc8c09a9cc119e608e6/pygradle-plugin/src/main/groovy/com/linkedin/gradle/python/extension/PythonDetails.java#L40) attributes in [PythonDetails.java](https://github.com/linkedin/pygradle/blob/master/pygradle-plugin/src/main/groovy/com/linkedin/gradle/python/extension/PythonDetails.java) as transient.

But I'm not sure that's the best approach.  I'm much more of a Python guy than a JVM guy.
Thoughts?

**Comment by kopy07** [comment]
Nice find! I'm working on a PR right now. I should have it open in the next few hours for you to take a look at.

**Comment by chrisbrake** [comment]
Thanks!
Just tested and confirmed the issue is resolved in your branch.

I'll close this issue and leave a comment on the PR.
