### ISSUE TITLE
Example of using PyGradle in Intellij Idea

### ISSUE THREAD

**Issue by sonalgupta** [linkedin/pygradle#41]
I am experimenting with the example-project and trying to have both Java and Python code in one repo. In Intellij Idea, if I set the `venv` directory as the SDK then it doesn't understand Java and vice-versa. I am new to Gradle, and thus, PyGradle. Can someone please tell me or add an example of a project that uses both Java and Python, and the directions of importing it to an IDE (preferably, Intellij Idea)?

**Comment by ethankhall** [comment]
@sonalgupta IntelliJ doesn't play nicely (out of the box) with Java and Python at the same time. It doesn't have a nice way to set the sdk for each module. What I end up doing is adding the following to a python project:

```
apply plugin: 'idea'
idea {
  module {
    sourceDirs += file('src')
    testSourceDirs += file('test')
    excludeDirs += project.buildDir
    excludeDirs += file('dist')
  }
}
```

Then IntelliJ will understand where the sources are, but won't know about the venv, then you manually add the venv when in IntelliJ. I have't found a better solution, but I also haven't spent a lot of time looking for one.

One issue I can think of is that IntelliJ holds all the SDK's that it can use in a global shared location which makes it strange to try to have Gradle configure it to know about the Python SDK out of the box.

**Comment by ethankhall** [comment]
@sonalgupta were you able to get a project using pygradle working with intellij?

**Comment by sonalgupta** [comment]
I eventually created a different module in intellij for python code and changed the SDK for that. thanks for your help.

**Comment by fkorotkov** [comment]
I did also struggle with that. Created a quick tutorial on how to configure Python SDK for {py}gradle: https://medium.com/@fedor/setting-up-intellij-for-py-gradle-758770367858
