### ISSUE TITLE
:installProject Exception when running example-project

### ISSUE THREAD

**Issue by sonalgupta** [linkedin/pygradle#42]
I ran `gradlew -i build` in the example-project directory and got the following exception.
(Replaced the actual directory with `<DIR>`). This only happens when I copy the example-project directory out of the bigger pygradle folder to `<DIR>`. If I run the build command when the directory is not moved out of the bigger folder, it works. What am I missing?

```:installProject
Executing task ':installProject' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Install example-project ............................................. [STARTING]
Starting process 'command '<DIR>/example-project/build/venv/bin/python''. Working directory: <DIR>/example-project Command: <DIR>/example-project/build/venv/bin/python <DIR>/example-project/build/venv/bin/pip install --disable-pip-version-check --no-deps --editable <DIR>/example-project
Successfully started process 'command '<DIR>/example-project/build/venv/bin/python''
Obtaining file://<DIR>/example-project
No files/directories in <DIR>/example-project (from PKG-INFO)
:installProject FAILED
:installProject (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.561 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installProject'.
> Failed to install example-project. Please see above output for reason, or re-run your build using ``ligradle -i build`` for additional logging.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 3.286 secs
```

The gradle file is 
```
plugins {
  id "com.linkedin.python-sdist" version "0.3.9"
}

dependencies {
    python 'pypi:requests:2.9.1'
    test 'pypi:mock:1.3.0'
}

repositories {
   pyGradlePyPi()
}
```

**Comment by ethankhall** [comment]
Hey @sonalgupta,

I pulled the example-project out into a completely un-related directory and it built fine. How did you get the gradle wrapper when you copied example-project out?

Could you run `gradlew --version`?

**Comment by sonalgupta** [comment]
```------------------------------------------------------------
Gradle 3.0
------------------------------------------------------------

Build time:   2016-08-15 13:15:01 UTC
Revision:     ad76ba00f59ecb287bd3c037bd25fc3df13ca558

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.10.5 x86_64```

I realize the problem is that the directory `example_project.egg-info` is not present in the `example-project/src` directory -- which somehow I was able to generate once. How does that directory get generated?

**Comment by ethankhall** [comment]
Python should auto-generate it. Would you be able to run a clean build and paste the whole output to a gist?

**Comment by sonalgupta** [comment]
https://gist.github.com/sonalgupta/1fdac45d8a1d4a8ebb9051cc912fd6c8

**Comment by ethankhall** [comment]
Thanks, I know what the issue it, its a doc problem. After you run `generateSetupPy` you need to uncomment the lines at the bottom. I'll go update the docs to make this more clear.

**Comment by sonalgupta** [comment]
ah ha, it works now. thanks. I wonder how it generated the first time. I never uncommented those lines, as far as I remember. Is it possible to tell gradle to not run `:installProject`?

**Comment by ethankhall** [comment]
Technically, yes. But if you do that then your virtualEnv won't know about your source code and all your tests will not work.

**Comment by sonalgupta** [comment]
ok, thanks again for your help!

**Comment by ethankhall** [comment]
Yep no problem. I'll close this when the PR gets merged if that's OK.

**Comment by zvezdan** [comment]
Merged.
