### ISSUE TITLE
no main manifest attribute, in pivy-importer jar

### ISSUE THREAD

**Issue by sonalgupta** [linkedin/pygradle#45]
I am trying to run the following command from the directory `/pygradle/build/pivy-importer/libs` after running `gradlew build` inside `pivy-importer`:

`java -jar pivy-importer-0.3.16-SNAPSHOT.jar --repo /tmp/libs/ virtualenv:15.0.1 pip:7.1.2`

along the lines of the example command in the docs `java -jar pivy-importer.jar --repo /path/to/destination virtualenv:15.0.1 pip:7.1.2`

and it gives the error:

`no main manifest attribute, in pivy-importer-0.3.16-SNAPSHOT.jar`

Is there any other way to generate the jar file that has the main manifest attribute?

**Comment by sonalgupta** [comment]
I have found ways around to create the `ivy-repo` repo. First, to run `importRequiredDependencies` task instead of `build`. Second, to untar the `pivy-importer-0.3.16-SNAPSHOT.tar` file in `distributions` and run the java class manually. Something like `java -cp 'pivy-importer-0.3.16-SNAPSHOT/lib/*' com.linkedin.python.importer.ImporterCLI --repo /tmp/libs/ virtualenv:15.0.1 pip:7.1.2 --replace alabaster:0.7=alabaster:0.7.1 ... `

It will be great to have better documentation on this.

**Comment by ethankhall** [comment]
I'll take a look tomorrow for it. I thought it had a Main Method attribute. Sorry about the confusion.

**Comment by ethankhall** [comment]
@sonalgupta I've opened a PR that updates the docs on how to use the pivy-importer, could you give them a once over to make sure they make since to you?

**Comment by sonalgupta** [comment]
@ethankhall added my comments.

**Comment by ethankhall** [comment]
Updated the PR and added a full example with expected output.
