### ISSUE TITLE
How to point to internal PIP repo for installations and how to publish artifacts to Artifactory and/or PIP ?

### ISSUE THREAD

**Issue by kavink** [linkedin/pygradle#51]
When i try to run build it tries to reach out to default pip repo. I have my .pip/pip.conf configured to point to internal repo. 

Please can you let me know how can i configure it to use an internal repo ? 
```
12:01:05     Complete output from command python setup.py egg_info:
12:01:05     Download error on https://pypi.python.org/simple/setuptools_scm/: [Errno 101] Network is unreachable -- Some packages may not be found!
```

As a second question, How do i publish tar.gz to artifactory or to pip repo ? I tried publications closure does not seem to work . Thoughts ?

**Comment by ethankhall** [comment]
@zvezdan can you look at the pip part? If I had to take a guess, it would be that something tries to install something that has a setup-requires section that's downloading the dependency.

What issue are you running into with publishing?

**Comment by kavink** [comment]
@ethankhall Thanks for replying! Sorry i just could not find example or task which publishes tar.gz to artifactory or pip. (Sorry!)

I did try using publications of gradle, but maybe I'm doing something wrong there.

**Comment by ethankhall** [comment]
Let me take a look tomorrow and I'll try to add it to the example project.

**Comment by zvezdan** [comment]
Yes, `setuptools_scm` is in `setup_requires` of one of your dependencies, and `setup_requires` are not processed by `pip`. Instead, they are processed by `setuptools` and only `install_requires`, `extras_require`, and `tests_require` are passed to `pip`. You can set `[easy_install]` section in various kinds of files (`setup.cfg` or your distutils config files). See http://setuptools.readthedocs.io/en/latest/easy_install.html#restricting-downloads-with-allow-hosts for info how to do that. We are working on a solution for this that can be generic enough to be added to {py}gradle as opposed to being specific to LinkedIn builds only. In the meantime, you can derive a custom solution from the docs above for your use case.

**Comment by ethankhall** [comment]
@kavink if you add the 'ivy-publish' plugin to the example, and add the following snippit 

```
publishing {
  publications {
    ivy(IvyPublication) {
      organisation 'org.gradle.sample'
      module 'project1-sample'
      revision '1.1'
      artifact source: tasks.packageSdist.getSdistOutput(), builtBy: tasks.packageSdist
    }
  }
  repositories {
    ivy {
      url "$buildDir/local-repo"
      layout('ivy')
    }
  }
}
```

If you run `gradle publish`, grade will publish the artifacts to a local repo. For more customizations on how to publish to your Artifactory, check out https://docs.gradle.org/current/dsl/org.gradle.api.publish.ivy.IvyPublication.html

**Comment by ethankhall** [comment]
I'm going to close this, please re-open the issue if it's still a problem.

**Comment by Bnsl-shbm** [comment]
I tried this approach and able to publish. but my ivy.xml does not have any dependency defined in it. Can you please suggest how to do it?
