### ISSUE TITLE
Issue building with pygradle and local pypi repository

### ISSUE THREAD

**Issue by similityman** [linkedin/pygradle#56]
I have created a local pypi repository using pyivy-importer and referring to the dependencies accordingly. Here is the completely build.gradle:

```
plugins {
    id "com.linkedin.python-sdist" version "0.3.9"
}

dependencies {
    python 'pypi:requests:2.11.1'
    python 'pypi:pandas:0.18.1'
    python 'pypi:PyYAML:3.11'
    test 'pypi:mock:2.0.0'
}

repositories {
    // This repository is provided for example purposes only
    ivy {
        name 'pypi-local'   //optional, but nice
        url '<DIR>/pypi'
        layout "pattern", {
          ivy "[organisation]/[module]/[revision]/[module]-[revision].ivy"
          artifact "[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]"
          m2compatible = true
        }
    }
}
```

I know that the pypi reference is being done correctly. However I am still getting the following errors. Do I need to override the dependency version for each task. The reason I ask is because when I created the local pypi repository using pyivy-importer, as an example, setuptools version 19.1.1 was never installed. All I have are version 11.3, 18.5 and 27.3.0. So how do I tell gradle to look for setuptools version 27.3.0 and not 19.1.1. There are other similar failures.

```
* What went wrong:
Execution failed for task ':installSetupRequirements'.
> Could not resolve all dependencies for configuration ':setupRequires'.
   > Could not find pypi:setuptools:19.1.1.
     Searched in the following locations:
         file:/<DIR>/pypi/setuptools/19.1.1/setuptools-19.1.1.ivy
         file:/<DIR>/pypi/setuptools/19.1.1/setuptools-19.1.1.jar
     Required by:
         :data-ingestion-scripts:unspecified
```

**Comment by zvezdan** [comment]
We keep some packages, such as virtualenv, setuptools, wheel, pip, ..., pinned to specific versions that we confirmed through thousands of builds to work with wide variety of packages and Python versions. You can find the currently pinned versions in PythonExtension.groovy.

If you don't want to install these specific versions, we also provide a way to override (add/change) the versions as an end user or custom internal plugin maintainer.
You can put in your build.gradle file:
```
python {
    forceVersion('pypi', 'pip', '7.1.2')
}
```
or a similar call if you decide to write an internal plugin with custom overrides.

**Comment by similityman** [comment]
Thanks @zvezdan that worked. Alternatively I actually regenerated the ivy repository using pyivy-importer with specific versions of packages that pygradle is advising to use and per you since thousands of builds have been tested with those versions.
