### ISSUE TITLE
How do I generate test and code coverage reports?

### ISSUE THREAD

**Issue by similityman** [linkedin/pygradle#57]
Actually giving more examples as to how do I generate unit-test (nose), pylint and code coverage (coverage) reports will be helpful.

**Comment by ethankhall** [comment]
Right now we only support pytest and flake8, but the code should be easy to extend to do that. We accept PR's :-)

**Comment by similityman** [comment]
Thanks @ethankhall I will be happy to try. Can you point me in that direction? New to Gradle and Groovy.

**Comment by ethankhall** [comment]
I would take https://github.com/linkedin/pygradle/blob/master/pygradle-plugin/src/main/groovy/com/linkedin/gradle/python/tasks/Flake8Task.groovy and rename it to something like CodeQualityTask and then add a field to set different style checkers (flake8 or pylint) then override `preExecution` to set the commandline args needed for setting the right args to run the tool. Then do the same-ish thing for the PyTestTask. Does this help?

**Comment by zvezdan** [comment]
@similityman Notice that `py.test` actually supports running `nose` and `unittest` tests out-of-the-box **without any changes needed**. The {py}gradle will automatically run the tests in `<your-python-project-name>/test/` directory using `py.test` with the appropriate options. See the example project setup.cfg file. You can add to it any pytest options you need:
```
[pytest]
addopts = --ignore build/ --ignore dist/
```

We also have a `coverage` task already present. Running the `coverage` Gradle task after build will use the `coverage` (python package) to generate the coverage report for your project. Thus, probably no changes need to be done for the testing. We'll try to add more examples and docs.

BTW, we highly recommend to try using py.test for testing. Fixtures and regular asserts are much nicer than the old-style unittest or nose. See http://pytest.org for the docs.

For the use of pylint instead of flake8, we deliberately chose not to enforce a checker that actually executes your code (pylint) because it can have unexpected side-effects. As Ethan mentions above, it is possible to add a pluggable checker, if you want.

**Comment by similityman** [comment]
@ethankhall - thanks for pointing out. I get it. One question though. I do not want to enforce running PyLint and Coverage by default. That is the enforcement should be user enabled. E.g this is what part of my build.gradle looks for a Java project project:

```
// findbugs tasks
findbugs {
    reportLevel = "high"
    ignoreFailures = false
}

tasks.withType(FindBugs) {
    reports {
        xml.enabled false
        html.enabled true
    }
}

// checkstyle tasks
checkstyle {
    ignoreFailures = false
}

tasks.withType(Checkstyle) {
    reports {
        xml.enabled false
        html.enabled true
    }
}
```

I am only enabling FindBugs and Checkstyle with explicitly mentioning their section in build.gradle. Similarly I would like to do that for PyLint and Coverage too.

**Comment by similityman** [comment]
@zvezdan - I didn't notice your comment until I replied to @ethankhall . I will checkout your suggestion. Much appreciated!

**Comment by similityman** [comment]
@zvezdan - I could use pytest and that is fine. I will also be fine with static analyzer like flake8 but how do I use the coverage task? I do see this https://github.com/linkedin/pygradle/blob/master/pygradle-plugin/src/main/groovy/com/linkedin/gradle/python/tasks/PyCoverageTask.groovy but how do I use it in build.gradle?

**Comment by similityman** [comment]
as simple as this huh..../gradlew build coverage

**Comment by zvezdan** [comment]
@similityman 

Correct. Also, if you already have a build: `./gradlew coverage` will run just coverage for you.

**Comment by similityman** [comment]
Right. got confused whether to include it in build.gradle or run it on command line. Anyway what about this:

```
:coverage
Unknown option: --
usage: <DIR>/build/venv/bin/python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
:coverage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':coverage'.
> Neither path nor baseDir may be null or empty string. path='null' basedir='<DIR>'
```

Something to do with this from PyCoverageTask.groovy?
```groovy
    public void preExecution() {
        args('--cov',
            project.file(component.srcDir).getAbsolutePath(),
            '--cov-report=xml',
            '--cov-report=html',
            '--cov-report=term')

        super.preExecution()
    }
```
Do I need to do anything more inside build.gradle?

**Comment by zvezdan** [comment]
Do you have a `test` directory inside your Python project?
See the example project for the code structure: https://github.com/linkedin/pygradle/tree/master/examples/example-project

**Comment by similityman** [comment]
I do

```
$ ls
README.md		build			config.yaml		gradlew			pinned.txt		setup.cfg		test
activate		build.gradle		gradle			gradlew.bat	setup.py		src

$ ls test/
__pycache__	test_cleanup.py
```

**Comment by zvezdan** [comment]
@similityman It seems that we broke that task while removing some LinkedIn internal features.
We'll try to fix ASAP.
Thanks for notifying us!

**Comment by similityman** [comment]
@zvezdan - Thanks for the promptness. Overall great work on the plugin by the team.

**Comment by zvezdan** [comment]
@similityman The version 0.3.23 released today has the fixed coverage task.

**Comment by similityman** [comment]
@zvezdan - Thanks for informing. I guess I don't have to do anything special as long as my build pulls in latest com.linkedin.python-sdist plugin?

**Comment by zvezdan** [comment]
Correct. The 0.3.24 is already out, so if you're pulling that in, you should be fine.

**Comment by zvezdan** [comment]
Closing the issue since it is fixed in the release 0.3.23 or higher.

**Comment by busche** [comment]
Just for future reference, I cite the official web page of py.test, which tells that
"pytest will run all files in the current directory and its subdirectories of the form test_*.py or *_test.py"

Therefore, the naming of the test suites is important (e.g., SomeTest.py does not work, though Some_test.py does).

**Comment by zvezdan** [comment]
@busche 

Correct. The default pattern for standard library `unittest` module is `test*.py`: https://docs.python.org/3.5/library/unittest.html#unittest-test-discovery and https://docs.python.org/2.7/library/unittest.html#unittest-test-discovery

Other test runners, such as `nose`, `zope.testrunner`, `py.test`, ..., just follow the suit with the same default pattern. The default can be changed, though, by defining the pattern in options/configuration. The details on how to do that is in the documentation for each runner. The nice thing about pytest is that it executes existing `unittest` or `nose` tests without any changes and has a natural `assert` syntax.

Internally, at LinkedIn we generate skeleton for new projects that has the `test` directory and inside it a `test_packagename.py`. The developers then add other test files as needed and we follow the practice of naming them `test_....py`. For example of the code structure, see the directory tree in the example project's README: https://github.com/linkedin/pygradle/tree/master/examples/example-project
