### ISSUE TITLE
use /usr/bin/env interpreter for pex

### ISSUE THREAD

**Issue by ags799** [linkedin/pygradle#72]
While using the `python-pex` plugin version 0.3.9, generated `.pex` files use the Python interpreter in `venv`. This inhibits their portability. [Per the pex documentation](https://pex.readthedocs.io/en/stable/whatispex.html#tl-dr) they ought to use `#!/usr/bin/env python`.

**Comment by zvezdan** [comment]
@ags799 
We fixed that bug in PR #52.
The front page has the link to the latest release: https://github.com/linkedin/pygradle 
As of today that's 0.3.29.
Please update to the latest.

We do not use `/usr/bin/env python`, but rather the Python that users specify during the build. A pex file built with Python 2.7 may fail with Python 2.6 and will definitely fail with Python 3.5. So, using `/usr/bin/env python` is not a guarantee of portability at all.

By default `/usr/bin/python` is used, but if users specify
```
python {
    details.pythonVersion = '3.5'
}
```
We'll use `/path/to/python3.5`. If users don't have `python3.5` in the `PATH`, they can provide additional paths:
```
python {
    details.prependExecutableDirectory(new File('/some/path/here'))
    // or details.appendExecutableDirectory(new File('/some/path/here'))
    details.pythonVersion = '2.7'
}
```

This allows enterprises to provide clean untainted interpreters of several supported Python versions that are installed/imaged on all the data center nodes and build hosts in their respective paths. Thus, a pex file can reliably get the Python version it was built for.

**Comment by ags799** [comment]
Thanks, and sorry for submitting this, my mistake!

**Comment by IvanAtanasov** [comment]
Doesn't it make sense to set the shebang as suggested?

I want the pex file to run using the same version of python as it was build on but not necessarily on a python interpreter in the exact same location. 

Using '#!/usr/bin/env python3.3' would achieve this.

Could there possibly be an option to set a custom shebang for a pex file?
