### ISSUE TITLE
sdist does not get rebuilt when source changes

### ISSUE THREAD

**Issue by schakrava** [linkedin/pygradle#80]
The sdist task(SourceDistTask.java) is not properly configured with inputs/outputs to detect changes in source, for example. Deriving from AbstractPythonMainSourceDefaultTask instead of DefaultTask(present case) fixes this problem.

We should also exclude **/*.egg-info/ from source Inputfiles.

**Comment by JLLeitschuh** [comment]
I think that this can be fixed by adding `@OutputDirectory` to the `getDistDir` method in the task.
