### ISSUE TITLE
"setup.py sdist --dist-dir" command converts version numbers with `_` to `-`

### ISSUE THREAD

**Issue by JLLeitschuh** [linkedin/pygradle#84]
This seems to be the opposite of what the `setup.py bdist_egg` command does.

When `setup.py sdist` encounters a version with an `_` character in it the resulting `tar.gz` file has the version converted to a `-`

So a version `'gradleBuild_2016111701.preview'`

Creates a `tar.gz` with the name: `$project.name-gradleBuild-2016111701.preview.tar.gz`

The `getSdistOutput` method in `SourceDistTask` should handle this.

**Comment by zvezdan** [comment]
This obviously needs to be fixed for such version "numbers".

However, neither underscore, nor dash should be used in the version.
This is the output of `python setup.py sdist` command for both:
```
setuptools/dist.py:293: UserWarning: The version specified ('2.5.4-whatever') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```
```
setuptools/dist.py:293: UserWarning: The version specified ('2.5.4-whatever') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```
So, with a future update of setuptools, we can fully expect such version "numbers" to cause an error.
