### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by scphantm** [linkedin/pygradle#92]
Am i missing something or is pygradle not compatible with Windows?  I added it to a Java project so I can enable sphinx and i get the error

```
Error:(16, 0) Unable to find or execute python
<a href="openFile:C:\code\SDA\build.gradle">Open File</a>

```

now this worked perfectly on my Mac, I was actually very excited.  so i did some digging and i found this in `com.linkedin.gradle.python.extension.PythonDetails` 

```
    private void findPythonWhenAbsent() {
        if (pythonInterpreter == null) {
            File python = ExecutablePathUtils.getExecutable(searchPath, "python");
            if (python == null) {
                python = new File("/usr/bin/python");
            }
            setSystemPythonInterpreter(python.getAbsolutePath());
        }
    }
```

and this in `com.linkedin.gradle.python.util.internal.ExecutablePathUtils`

```
    public static File getExecutable(List<File> pathList, String exeName) {
        for (File dir : pathList) {
            File candidate = new File(dir, exeName);
            if (candidate.isFile()) {
                return candidate;
            }
        }
        return null;
    }
```

Neither method takes into account that on a Winblows machine the executable name is `python.exe` and not `python`.  And in my situation, this code is run on Winblows, Mac, and Linux so hard coding the thing in the build.gradle isn't practical.

Am I right or am I missing something?

**Comment by zvezdan** [comment]
@scphantm The code you pointed to was actually recently added to provide compatibility with Windows. See PR #90 for details.
However, this does require that you add a path where your Python interpreter can be found.
```groovy
python {
    details.prependExecutableDirectory(path)    // path is a File object here
}
```
Let me know if you need any other info.

**Comment by scphantm** [comment]
But i can't create a path object in my build.gradle file because some developers use Mac, some use linux, some use windows and our CI server is linux.  whats wrong with the good old fashioned

if (os == 'win') { exe = "python.exe"} else { exe = 'python' } 

loop path looking for it?  The moment you start specifying paths in the build.gradle file you hose out my CI servers, because they absolutely do not match development machines.  not even close.

**Comment by sixninetynine** [comment]
Could you only define the path on windows? 

something like:
```
String osName = System.getProperty("os.name").toLowerCase();
if (osName.contains("windows")) {
...
}
```

**Comment by scphantm** [comment]
first of all, don't use system.getproperty.  use 

```
import org.apache.tools.ant.taskdefs.condition.Os
static String operatingSystem(){
        if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            'win'
        } else if (Os.isFamily(Os.FAMILY_MAC)) {
            'mac'
        } else if (Os.isFamily(Os.FAMILY_UNIX)) {
            'nix'
        } else {
            null
        }
    }
```

far less compatibility issues with various operating systems like BSD and some of the more obscure offshoots.  

Second.  My organization has 1200 projects that we are converting to Gradle over the next year.  We want pygradle in the mix.  Could you please justify why I would have to copy that snip into 1200 different build.gradle files instead of just fixing the search method to know the difference between windows and not windows?

**Comment by sixninetynine** [comment]
I was merely asking the question with a simple example... manual maintenance of ~1200 build files is a reasonable enough answer as to "why not". I'll defer to my colleagues @ethankhall and/or @zvezdan on your second question. Though I'm a bit confused by your tone, I hope I didn't give you the impression that we aren't interested in your problem! We certainly are!

**Comment by scphantm** [comment]
If its an oversite, then I'm trying to fix it, if it was designed that way im trying to understand why.  but at the moment I can't get pygradle to compile on my Winblows machine.  But i think that has more to do with our retarded firewall rules than the code. (wouldn't be the first time) but if i can't, i have no way to test the patch before submitting the PR as all my other machines are Mac and Linux.  

I'm still trying to figure that one out.

**Comment by zvezdan** [comment]
@scphantm 
Thank you for explaining your use case.
Here's some background information that can help you make decisions on your side as well.

During the open-sourcing of pygradle, we had to remove a lot of things specific to LinkedIn and make pygradle usable in a generic environment for any user. However, we do have some very specific extensions, plugins, and settings that we still needed to be able to run. So, we added a lot of flexible settings that allow users to change the things for simpler builds in the project's _build.gradle_ file, or for more complex usage in their _custom plugins_ that apply pygradle.

For example, we internally use our specific Python interpreters that are available on all our machines. So, we had to provide the way to prepend/append the paths to interpreters to support our own builds in the same way they worked before open-sourcing.

There are many other examples of such overrides for settings, internal extensions, and internal plugins that are not applicable outside our environment, as well as new features that we test internally before deciding to add them to the open-source pygradle.

All our products that use Python apply our _internal_ plugin. That plugin applies pygradle early on (`project.plugins.apply(PythonPlugin)`) and then proceeds to change settings, add internal extensions, ... That way, only our internal plugin needs to handle settings instead of requiring thousands of products to change their _build.gradle_ file.

From our experience this is the best way to control our build environment and adapt it to our specific needs. If you want to control a lot of products in the same way, please consider doing something similar and feel free to ask questions about that.

Regarding Windows, I need to point out that we do not build our products on Windows and pygradle is not extensively tested in that environment. Thus, there is a chance that some parts will need to be adjusted. We welcome suggestions for improvements (or pull requests).

**Comment by scphantm** [comment]
thats actually exactly the way i am structuring things.  stuff like pygradle's default source is src, but in mine i need it to be src/main/python.  Im handling that stuff in my wrapper.  but this one, I figured it was just an over site.  I will attempt to attach a PR if i can get the thing to build on my machine to fix this issue.

**Comment by scphantm** [comment]
I have a fix sorta running.  I had to conditionally ignore a few tests because they are shell based which crashes on windows.  Im going to probably need a little help with some replacement code for those.  But the more pressing problem is this.  I don't know enough about that dependency system to be able to really debug this.  Any ideas where i can start?  Keep in mind, this is most certainly a Winblows specific problem.

```
9:13:24 PM: Executing external tasks 'clean build'...
Parallel execution with configuration on demand is an incubating feature.
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:pluginDescriptors UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:pluginUnderTestMetadata UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:validateTaskProperties UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
Using the 'clean' task in combination with parallel execution may lead to unexpected runtime behavior.
Building using version 0.3.38-SNAPSHOT
[buildinfo] Not using buildInfo properties file for this build.
:pivy-importer:clean
:pygradle-plugin:clean
:pivy-importer:compileJava UP-TO-DATE
:pivy-importer:compileGroovy
:pygradle-plugin:compileJava UP-TO-DATE
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:pygradle-plugin:compileGroovy
warning: [options] bootstrap class path not set in conjunction with -source 1.7
:pivy-importer:processResources
:pivy-importer:classes
:pivy-importer:jar
:pivy-importer:startScripts
:pivy-importer:distTar
1 warning
:pivy-importer:distZip
:pivy-importer:groovydoc
Trying to override old definition of task fileScanner
Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
line 69:57: unexpected token: >
ERROR [org.codehaus.groovy.tools.groovydoc.GroovyRootDocBuilder] ignored due to RecognitionException: com\linkedin\python\importer\ImporterCLI.java [expecting EOF, found 'for']
:pygradle-plugin:pluginDescriptors
:pygradle-plugin:processResources
:pygradle-plugin:classes
:pygradle-plugin:jar
:pygradle-plugin:groovydoc
Trying to override old definition of task fileScanner
:pivy-importer:javadocJar
:pivy-importer:sourceJar
:pivy-importer:assemble
line 52:52: unexpected token: >
line 53:13: unexpected token: PythonExtension
line 54:13: unexpected token: PythonDetails
line 55:13: unexpected token: String
line 58:12: unexpected token: List
line 61:12: unexpected token: FileCollection
:pivy-importer:checkstyleMain
ERROR [org.codehaus.groovy.tools.groovydoc.GroovyRootDocBuilder] ignored due to RecognitionException: com\linkedin\gradle\python\tasks\AbstractPythonMainSourceDefaultTask.java [expecting EOF, found 'componentFiles']
line 81:27: expecting SEMI, found ','
ERROR [org.codehaus.groovy.tools.groovydoc.GroovyRootDocBuilder] ignored due to RecognitionException: com\linkedin\gradle\python\tasks\BuildWebAppTask.java [expecting EOF, found 'options']
line 40:44: unexpected token: >
ERROR [org.codehaus.groovy.tools.groovydoc.GroovyRootDocBuilder] ignored due to RecognitionException: com\linkedin\gradle\python\util\internal\ExecutablePathUtils.java [expecting EOF, found 'String']
line 82:47: unexpected token: >
ERROR [org.codehaus.groovy.tools.groovydoc.GroovyRootDocBuilder] ignored due to RecognitionException: com\linkedin\gradle\python\util\internal\pex\PipFreezeAction.java [expecting EOF, found 'for']
line 34:43: unexpected token: >
ERROR [org.codehaus.groovy.tools.groovydoc.GroovyRootDocBuilder] ignored due to RecognitionException: com\linkedin\gradle\python\util\internal\pex\PipFreezeOutputParser.java [expecting EOF, found 'for']
line 66:23: expecting SEMI, found ','
ERROR [org.codehaus.groovy.tools.groovydoc.GroovyRootDocBuilder] ignored due to RecognitionException: com\linkedin\gradle\python\util\internal\pex\ThinPexGenerator.java [expecting EOF, found 'propertyMap']
:pivy-importer:compileTestJava UP-TO-DATE
:pivy-importer:compileTestGroovy UP-TO-DATE
:pivy-importer:processTestResources UP-TO-DATE
:pivy-importer:testClasses UP-TO-DATE
:pivy-importer:checkstyleTest UP-TO-DATE
:pivy-importer:codenarcMain
:pygradle-plugin:javadocJar
:pygradle-plugin:sourceJar
:pygradle-plugin:assemble
:pygradle-plugin:compileIntegTestJava UP-TO-DATE
:pygradle-plugin:compileIntegTestGroovy
:pygradle-plugin:processIntegTestResources
:pygradle-plugin:integTestClasses
:pygradle-plugin:checkstyleIntegTest UP-TO-DATE
:pygradle-plugin:checkstyleMain
:pygradle-plugin:compileTestJava UP-TO-DATE
:pygradle-plugin:compileTestGroovy
:pygradle-plugin:processTestResources
:pygradle-plugin:testClasses
:pygradle-plugin:checkstyleTest UP-TO-DATE
:pygradle-plugin:codenarcIntegTest
CodeNarc completed: (p1=0; p2=0; p3=0) 9267ms
:pivy-importer:codenarcTest UP-TO-DATE
:pivy-importer:licenseMain UP-TO-DATE
:pivy-importer:licenseTest UP-TO-DATE
:pivy-importer:license UP-TO-DATE
:pivy-importer:test UP-TO-DATE
:pivy-importer:check
:pivy-importer:shadowJar
CodeNarc completed: (p1=0; p2=0; p3=0) 1799ms
:pygradle-plugin:codenarcMain
:pygradle-plugin:codenarcTest
:pivy-importer:build
:pivy-importer:importRequiredDependencies
alabaster:0.7=alabaster:0.7.1
pytz:0a=pytz:2016.4
Babel:0.8=Babel:1.0
sphinx_rtd_theme:0.1=sphinx_rtd_theme:0.1.1
chardet:2.2=chardet:2.3.0
setuptools:0.6a2=setuptools:19.1.1
idna:2.0.0=idna:2.0
docutils:0.12
CodeNarc completed: (p1=0; p2=0; p3=0) 1234ms
:pygradle-plugin:test
21:14:07.698 INFO  c.l.p.i.deps.DependencyDownloader - Pulling in virtualenv:15.0.1
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 5: https://pypi.python.org/packages/c8/82/7c1eb879dea5725fae239070b48187de74a8eb06b63d9087cd0a60436353/virtualenv-15.0.1.tar.gz
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:46)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.linkedin.python.importer.deps.DependencyDownloader.downloadArtifact(DependencyDownloader.groovy:82)
	at com.linkedin.python.importer.deps.DependencyDownloader$downloadArtifact$0.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:214)
	at com.linkedin.python.importer.deps.DependencyDownloader.downloadDependency(DependencyDownloader.groovy:70)
	at com.linkedin.python.importer.deps.DependencyDownloader$downloadDependency.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.linkedin.python.importer.deps.DependencyDownloader.download(DependencyDownloader.groovy:49)
	at com.linkedin.python.importer.ImporterCLI.main(ImporterCLI.java:73)
:pivy-importer:importRequiredDependencies FAILED
Task :pygradle-plugin:test results: SUCCESS (50 tests, 43 successes, 0 failures, 7 skipped)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pivy-importer:importRequiredDependencies'.
> Process 'command 'C:\HighmarkApps\MyEclipse Blue Edition 2016\binary\com.sun.java.jdk8.win32.x86_1.8.0.u66\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 55.69 secs
Process 'command 'C:\HighmarkApps\MyEclipse Blue Edition 2016\binary\com.sun.java.jdk8.win32.x86_1.8.0.u66\bin\java.exe'' finished with non-zero exit value 1
9:14:20 PM: External tasks execution finished 'clean build'.

```

**Comment by scphantm** [comment]
I could really use some help on the cross platform unit tests.  I still havn't gotten the virtual environment to work, but i am working on the unit tests.  I suspect when I get the units running, the venv will do something other than crash.

The problem i am having with the unit tests are the different ways OS's load the exe.  so for nix/mac, python 2 would be `/bin/python2` or `/bin/python2.7`.  but on windows it would be `c:\mystuff\python2\python.exe` or c:\folder i will never remember\pythondunnoversion\python.exe'  now that is well and good, the problem is on windows i have no way of determining what version of python I found without executing the exe (aka python.exe --version) using the version parser in the code.  Works great in the real world, but how do i setup that environment in the unit tests so it can be replicated on developers machines?  For example, my Win machine doesn't have python 2 installed.  Only python 3.5.  So none of the unit tests referencing python 2 will run. 

Anyone have any good ideas on how i can create a virtual os environment and run the tests?  For example, for me to be very happy, i need your CI server to execute the tests intended for windows machines.  which means the ci server needs to be able to replicate a windows environment, all the way down to executing a windows exe somehow to determine what version of python it is.  

any ideas?

**Comment by scphantm** [comment]
https://github.com/linkedin/pygradle/pull/95 BTW

**Comment by ethankhall** [comment]
@scphantm It looks like the Windows impl of Path doesn't support file paths.

```
diff --git a/pivy-importer/src/main/groovy/com/linkedin/python/importer/deps/DependencyDownloader.groovy b/pivy-importer/src/main/groovy/com/linkedin/python/importer/deps/DependencyDownloader.groovy
index e4e5877..8575169 100644
--- a/pivy-importer/src/main/groovy/com/linkedin/python/importer/deps/DependencyDownloader.groovy
+++ b/pivy-importer/src/main/groovy/com/linkedin/python/importer/deps/DependencyDownloader.groovy
@@ -20,10 +20,9 @@ import com.linkedin.python.importer.ivy.IvyFileWriter
 import com.linkedin.python.importer.pypi.PypiApiCache
 import com.linkedin.python.importer.util.ProxyDetector
 import groovy.util.logging.Slf4j
+import org.apache.commons.io.FilenameUtils
 import org.apache.http.client.fluent.Request

-import java.nio.file.Paths
-
 @Slf4j
 class DependencyDownloader {

@@ -79,7 +78,7 @@ class DependencyDownloader {

     static File downloadArtifact(File destDir, String url) {

-        def filename = Paths.get(url).getFileName().toString()
+        def filename = FilenameUtils.getName(new URL(url).getPath())g
         def contents = new File(destDir, filename)

         if (!contents.exists()) {
```

Should fix the issue and move from using Path to an Apache library.

Right now the way we get the version is by executing `python --version` to see what version it responds with. So I think thats probably what we want to keep doing.

What we do in some of our tests that are just going to validate that the parser works is to drop a file on the filesystem that will just echo out the value that we expect. It's not a perfect test, but it's ok for parsing code.

We probably want to start also running the tests against appveyor to make sure we don't break the Windows code as time moves on.

**Comment by scphantm** [comment]
I have some paying work to wrap up today before i jump on this.  but i gotta think there's some way to replicate the env for testing.  this isn't a unique problem.  I will dig a bit deeper and find it. I will look at that apache library, if it abstracts the differences between posix and dos file systems, i may be able to use that to generate a virtual OS file system that will meet our needs.  Then all i have to do is deal with the different locations and names for the two different systems.

And yea, the way you do the version today is the best way to do it.  i was just pointing out that its a platform dependant way because you can't execute a shell on a win box and can't execute a win32 on a nix box.

**Comment by scphantm** [comment]
ive been doing some digging and it appears the way that other teams deal with this is running virtualbox and executing the units on both environments.  Configuring appveyor may be our best bet, if you have an instance available.  Then a series of IgnoreIf statements

**Comment by ethankhall** [comment]
With was done in #104 I believe.
