### ISSUE TITLE
Remove the need for the "replace" functionality in pivy

### ISSUE THREAD

**Issue by derenrich** [linkedin/pygradle#99]
Seems like we shouldn't require end-users to use the replace functionality. Being explicit can be good in some cases but just automatically picking the newest version that satisfies the requirement would be nice.

It's really bad UX to constantly have to tell pivy "yeah there is no version 1.0.0, just use version 1.1.0".

**Comment by zvezdan** [comment]
@derenrich 
We improved pivy-importer in #138.
I was able to upload some newer versions of dependencies using the new `--latest` option without specifying any replace packages.
We also disallow pre-releases now by default (alpha, beta, rc), but there's a `--pre` option to allow them if needed.
Does this satisfy your needs too?

**Comment by derenrich** [comment]
Yeah
